### ISSUE TITLE
Пароль при логине

### ISSUE THREAD

**Issue by skinysmn** [leominov/khl-api-16-17#1]
Думаю передавать пароль в открытом виде не самый безопасный вариант. В md5 его закодировать более безопасный вариант

**Comment by leominov** [comment]
Привет, @skinysmn и спасибо за твой комментарий.

Ты абсолютно прав, но данный репозиторий лишь хранит описание API проекта, разработчиком или технологом которого я не являюсь; информация о доступных методах была получена в ходе исследования работы официального приложения KHL.

Стоит отметить, что для сезона 2017/2018 на стороне API был добавлен SSL, что усложняет, но не исключает, фишинг передаваемого пароля пользователя.

Описание проблемы безопасности приложения ты можешь направить на контактный e-mail: app@khl.ru
